### ISSUE TITLE
Upload waypoint to Crazyflie

### ISSUE THREAD

**Issue by J-Durotifa** [USC-ACTLab/crazyswarm#160]
Hi,

I have used the "Upload Trajectory" function in the crazyswarm library.

I would like to go a step further to be able to upload Waypoints (XYZ) and RGB data to the drone by radio, and play it back the same way that it's done with the 7th order Polynomial Trajectory.

Could you point me in the right direction of the files I need to look at in order to be able to do this?

**Comment by whoenig** [comment]
This is a bit of an effort since you will need to make firmware and client changes.

1. Firmware: You can add another trajectory type: https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/crtp_commander_high_level.c#L66, https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/crtp_commander_high_level.c#L360-L384. The evaluation would need to generate setpoints differently from the current implementation that evaluates the polynomials.

2. Crazyflie_cpp: Very similar to this function: https://github.com/whoenig/crazyflie_cpp/blob/master/src/Crazyflie.cpp#L1406-L1436, except that you use your own type rather than poly4d and you set a different trajectoryType.

3. crazyflie_ros: You need a new message type, similar to https://github.com/whoenig/crazyflie_ros/blob/master/crazyflie_driver/msg/TrajectoryPolynomialPiece.msg.

4. crazyswarm: Similar to the uploadTrajectory functionality, see https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/src/crazyswarm_server.cpp#L203, https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/src/crazyswarm_server.cpp#L353-L382, and https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/src/crazyswarm_server.cpp#L353-L382.
