### ISSUE TITLE
The difference between Mellinger controller and PID controller

### ISSUE THREAD

**Issue by swarm5** [USC-ACTLab/crazyswarm#268]
I want to use the `cmdVelocityWorld `command for experimental testing.
Today, I used this program:` crazyswarm/ros_ws/src/crazyswarm/scripts/cmdVelocityCircle.py`, but unfortunately, when I used the Mellinger controller, the experiment failed and cf  hit the wall;  However, when I used the PID controller, cf can fly very stably.
**In order to control the Velocity of cf, I now have two solutions:**
1. Use PID controller and use` cmdVelocityWorld `to control cf. But I don’t know what is the difference between PID controller and Mellinger controller? It seems that Mellinger controller is more recommended.
2. Use Mellinger controller and use `cmdFullState` to approximate it.

Do you have any suggestions?

**Comment by jpreiss** [comment]
Use PID. We tuned the mellinger controller for tracking physically plausible smooth trajectories with position, velocity, acceleration, and angular velocity terms. It has very high gains because those smooth trajectories can be tracked with low error. It needs more tuning (or even code changes) to work well with something like a step velocity input.

**Comment by swarm5** [comment]
thanks
