### ISSUE TITLE
Motive 2.0 with VRPN streaming (Unknown motion capture type!

### ISSUE THREAD

**Issue by elim17** [USC-ACTLab/crazyswarm#298]
Hello,

I was referencing the issue below as our lab is using vrpn with motive Optitrack.[https://github.com/USC-ACTLab/crazyswarm/issues/121](url). When I run hover_swarm.launch the server dies because of a runtime_error "Unknown motion capture type". I know it is the motion capture type parameter in the launch file, because when I change the parameter to Optitrack,  the server launches and stays running. However, when I hit the start button on the controller it still doesn't fly. Any ideas?

**Comment by whoenig** [comment]
I think VRPN is not compiled by default anymore, because of issues with Ubuntu 20.04/ROS melodic. However, there is no reason to use VRPN for an Optitrack system - the integrated optitrack support should be far superior to the VRPN mode.

To check your mocap, you can try launching `mocap_helper.launch` instead of `hover_swarm.launch`. If your drone isn't doing anything, it is likely a firmware issue, though - did you upgrade your Crazyradio as well as NRF firmwares?
