### ISSUE TITLE
ImportError for ROS generated modules in Python 2

### ISSUE THREAD

**Issue by santiagorg2401** [USC-ACTLab/crazyswarm#455]
Hi, I hope you're all doing well,
I am having trouble with the latest update, I re-installed everything related to crazyswarm on my PC but now when I try to run a script (even with the provided ones) I get:

```
Traceback (most recent call last):
  File "niceHover.py", line 9, in <module>
    swarm = Crazyswarm()
  File "/home/santiagorg2401/crazyflie/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyswarm.py", line 50, in __init__
    from .crazyflie import TimeHelper, CrazyflieServer
  File "/home/santiagorg2401/crazyflie/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyflie.py", line 12, in <module>
    from crazyswarm.srv import *
ImportError: No module named srv
```

I already tried re-installing again several times but that didn't work.

Thank you for your time.

**Comment by whoenig** [comment]
I just tested it and it seems to work. Did you forget to call `source devel/setup.bash` in the terminal that you use to launch the script from?

**Comment by santiagorg2401** [comment]
Hi, I sourced in the terminals when I got the error, it only happens in non-simulations execution, in other words, when running with --sim it doesn't happen.

**Comment by The-SS** [comment]
I had this issue on Ubunut 16.04 with Python 2. It might be related to [this](https://answers.ros.org/question/52790/no-module-named-srv/), tl;dr, python confuses the file name and the ros package name.
I solved it by renaming `pycrazyswarm/crazyswarm.py` to `pycrazyswarm/crazyswarm_py.py` , and editing `pycrazyswarm/__init__.py`: instead of `from .crazyswarm import *` use `from .crazyswarm_py import *`.

**Comment by whoenig** [comment]
I did test with real flight. The `--sim` option actually doesn't use ROS at all and therefore doesn't try to import the service description. I tested on Ubuntu 20.04, ROS Noetic, Python 3.

**Comment by santiagorg2401** [comment]
I forgot to tell you my Ubuntu version (my bad), I have Ubuntu 18.04, ROS Melodic & Python 2.

**Comment by The-SS** [comment]
Yes, this seems to be a Python 2 issue.

**Comment by santiagorg2401** [comment]
Well, I installed Ubuntu 20 but now I have trouble installing, however, I'll open another issue for that.

**Comment by cscholler** [comment]
> I had this issue on Ubunut 16.04 with Python 2. It might be related to [this](https://answers.ros.org/question/52790/no-module-named-srv/), tl;dr, python confuses the file name and the ros package name.
> I solved it by renaming `pycrazyswarm/crazyswarm.py` to `pycrazyswarm/crazyswarm_py.py` , and editing `pycrazyswarm/__init__.py`: instead of `from .crazyswarm import *` use `from .crazyswarm_py import *`.

Using Melodic on Ubuntu 18.04 with python 2 I was having this same "No module named srv" import error. Renaming these files and removing pycrazyswarm.pyp fixed it for me.

**Comment by jpreiss** [comment]
I saw this today too. I am guessing this bug was introduced by 9037a25c8390fbc68f1dc335f8131545d6cb6012. We should rename the file, I think.

It would be nice if we could catch bugs like this in CI. In descending order of usefulness (and effort), we could...

1. finish #350, then run all current unit tests with the ROS sim
2. make sure the server and pycrazyswarm still run when crazyflies.yaml contains 0 entries, and write a test to verify that we can spin ROS once
3. write a test to make sure we can import pycrazyswarm in ROS, but never actually construct the `Crazyswarm` object

**Comment by jpreiss** [comment]
failing test for option 3 (see previous comment) added in https://github.com/USC-ACTLab/crazyswarm/tree/rosCI_rebase

**Comment by jpreiss** [comment]
Renamed file on same branch. If someone could make a fresh `git clone` from that branch and verify they can run a script with real hardware under Python 2, that would be helpful.

**Comment by jpreiss** [comment]
did testing myself.
