### ISSUE TITLE
 ICP did not converge

### ISSUE THREAD

**Issue by pPatrickK** [USC-ACTLab/crazyswarm#57]
Hi guys,

Once the Server is running we face the following error, which occurs frequently:

[33m[ WARN] [1523545145.722350731]: ICP did not converge![0m
[33m[ WARN] [1523545145.722411588]: No updated pose for CF cf15 for 0.000666 s.[0m

How  can we fix this problem. We don't know why the algorithm doesn't converge. Are there any possibilities to configure our system? (eg adjustment parameters with which we can adjust its convergence performance.)

Best regards
Patrick

**Comment by whoenig** [comment]
Is that happening at startup while they are on the ground or while you are flying? Also, take a look at rviz, which shows you a point cloud as received from VICON and make sure that you get a stable point cloud.

If there is no additional information, there were likely no nearby detected markers. Otherwise it will tell you which dynamics check failed, and you can adjust it [here](https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/crazyflieTypes.yaml#L106-L114).

**Comment by pPatrickK** [comment]
Hi whoenig, 

first, thank you guys for the super quick response. 

1.
Regarding the stability of the pointcloud:
That might be the reason. We have a lot of the cameras at the ceiling.
Over 1000 frames the cluster has a span of ~0.2mm in x,y axis but ~5mm in z axis.

-> We are rearranging the cameras right now so that we have a better covering from the sides.

2. 
Both, the ICP error comes directly after the cf is connected and stays also during the flight.

3. 
Mostly the pitch and roll dynamic is to high which probably comes from the big noise in z axis.
Will it help if increase the thresholds? from what i have seen in the code, this frame from the mocap will be discarded and not incorporated in the pos estimate, right?


Is there a possibility to change some parameters in the algo to get it more robust? In tradeoff for precision.

I have some pictures of our environment attached, so that you can get an impression.


[20180123_MoCap System TU Dortmund.pdf](https://github.com/USC-ACTLab/crazyswarm/files/1907600/20180123_MoCap.System.TU.Dortmund.pdf)
![dsc_0182](https://user-images.githubusercontent.com/30862002/38739056-20bad038-3f34-11e8-9d18-a5612c7d766b.JPG)
![dsc_0183](https://user-images.githubusercontent.com/30862002/38739057-20d942fc-3f34-11e8-9379-35676e9e6cfa.JPG)
![dsc_0184](https://user-images.githubusercontent.com/30862002/38739058-20f81ac4-3f34-11e8-8e2f-be8ce19c08f1.JPG)
![dsc_0185](https://user-images.githubusercontent.com/30862002/38739060-21127ab8-3f34-11e8-9846-ab8f807ac769.JPG)

**Comment by whoenig** [comment]
1. If the VICON system is new, you can also check with VICON support - they usually have some good ideas on how to better place the cameras. The same goes for some more advanced settings, like strobe, aperture, and various thresholds that can be adjusted in Tracker to improve tracking performance. 

2. We do not see any of the ICP errors in normal operation. If you see the issues already while being on the ground, than either your marker configuration is wrong, or it is really caused by the noise you are seeing.

3. Our tracking is a two-step approach: a) we run standard ICP, and b) we discard outputs that are outside of the dynamic limits. You can tune both ICP parameters (see the PCL documentation for that purpose) and our dynamic limits, depending on which part is failing in your case. It will probably help to increase the dynamic limits - you just need to make sure that your marker configuration is asymmetric enough. The dynamic limit check is very important to reject incorrect ICP results where a CF flips in one frame (axis flip). Since ICP is a local optimization technique, we would not be able to recover after a wrong classification (frame-by-frame tracking).

> from what i have seen in the code, this frame from the mocap will be discarded and not incorporated in the pos estimate, right?

I am not sure what you mean? We do send position and quaternion over to the CF and use the full pose in the EKF state estimation. It is of course possible to disable that, but that you might suffer from yaw-drifts.

Adjusting the various parameters will make the system more "robust" in the case of your noisy input, but at the same time increases the risk of faulty tracking during operation. I'ld suggest to try to improve the raw point cloud tracking performance first, and after you see that you are at the limit of the VICON system, start adjusting the various tracking parameters.

Thank you very much for sharing the pictures - the setup looks very impressive. Our space is much smaller, but we also use fewer cameras (24, 8xVantage8, 16x Vantage5). You can see how we place the cameras in one of our videos, e.g., https://www.youtube.com/watch?v=OzXUV4GQ7Qs&feature=youtu.be. (The original Crazyswarm videos were shot when our space was not yet finalized).

**Comment by pPatrickK** [comment]
Hi whoenig,

we changed our camera configuration. We have now a better coverage from the sides, altough there is still more potential in it. The span of a marker in z axis is reduced to 1mm span over 1000 frames. We still get the ICP error sometimes, but only every few seconds now. 

Okay, thats what i meant. The cf gets no external position update if: 
1. the ICP does not converge
2. the dynamic check fails

Thanks again for the help.

Best regards,
Patrick

**Comment by whoenig** [comment]
How does ICP fail? If the dynamic check fails, it should tell you exactly which condition is violated and you can try adjusting the parameters. I guess that 1mm span should be actually fine - did you check if you have (in addition) sometimes disappearing markers?

**Comment by pPatrickK** [comment]
Our markers should be fine. The actual error message is:
```
[ WARN] [1524225043.689062761]: ICP did not converge!
[ WARN] [1524225043.689831724]: No updated pose for CF cf13 for 0.002842 s.
[pcl::IterativeClosestPoint::computeTransformation] Not enough correspondences found. Relax your threshold parameters.
```
This error occured with 10 drones on two channels. If we reduce the amount of drones, we get less _ICP did not converge_ errors. We found out that the amount of errors is drone dependent.

**Comment by pPatrickK** [comment]
We made now a reference for each drone itself due to the variation on the build -> helps.
We increased the dynamic and fitness threshold -> helps

**Comment by pPatrickK** [comment]
Hey Guys,

we still have a problem with the libobjecttracker, so we used the vicon system (motionCapture) for tracking. We would like to scale up the swarm so the libobjecttracker would be much better. Thats why we want do fix the problems permanently now.

We get much less errors, than the last time, but still the same errors as mentioned above.

> [ WARN] [1524225043.689062761]: ICP did not converge!
> [ WARN] [1524225043.689831724]: No updated pose for CF cf13 for 0.002842 s.
> [pcl::IterativeClosestPoint::computeTransformation] Not enough correspondences found. Relax your threshold parameters.


My question now: how and where do I have to implement this code:

> You can also try enable the verbose output of PCL (`pcl::console::setVerbosityLevel(pcl::console::L_VERBOSE);`; untested) to see why it didn't converge.

Best regards
Patrick
