### ISSUE TITLE
Firmware Controller

### ISSUE THREAD

**Issue by andresbhoo** [USC-ACTLab/crazyswarm#83]
Hi Whoenig,

I am trying to modify pieces of the on-board controller, but thus far I am unable to find the controller within the various firmware files on the crazyswarm github.

Sorry for the trouble. It feels like I am probably missing something in plane sight, but thus far I have had no luck.

Thanks for the help!

**Comment by andresbhoo** [comment]
Fantastic! Thank you.

**Comment by jpreiss** [comment]
You're welcome, please share with us if you make improvements to the controller!

**Comment by emmasmith100** [comment]
Hi there!
I have been going through the mellinger paper and the code controller_mellinger.c in order to understand its implementation.
I do have many questions below and I was wondering if someone knows the answers? THANKS A LOT FOR YOUR HELP!
Note: my level of C coding is very basic and since there are not many comments in the code it gets difficult for newcomers. Especially the used attitude representations (and the chosen conventions) are not always clear to me.

**Question1:** 
`#include "position_controller.h"`: why do you include this? I don’t see where this is used?

**Question2:**
I understand controller gains are static since they will never change during flight. Under the comments 
`// Helper variables` and `// Logging variables` you also defined e.g. `i_error_x, prev_omega_roll, static struct vec z_axis_desired, roll_desired` as static variables. But these are variables must be changing over time? So it seems I don’t fully understanding the concept static.
Related to this, why is e.g. `prev_omega_roll` not assinged to 0? 

**Question3:** 
`i_range_xy`: what's the procedure to choose the range to saturate/clamp the integral error? Is this clamping strictly necessary or should it also work without clamping?

**Question4:**
I don’t understand the use of the functions `controllerMellingerInit()` and `controllerMellingerTest()`, since there are not called in the code.

**Question5:**
Concerning the function 
```
void controllerMellingerNew(control_t *control, setpoint_t *setpoint,
                                         const sensorData_t *sensors,
                                         const state_t *state,
                                         const uint32_t tick)
```
I was able to find more information in `stabilizer_types.h`, but I have some questions related to that file.
**5a)** For` typedef struct quaternion_s`, what is the difference between these 2 representations (q0,q1,q2,q3) vs (x,y,z,w)? Are they fully equivalent? In `controller_mellinger.c` code, it seems only the second one is used. So why do you have 2 representations?
**5b)** Are the quaternion representations _unit_ quaternions? Which _convention_ do you assume through the code? Hamilton or JPL? https://fzheng.me/2017/11/12/quaternion_conventions_en/
**5c)** `typedef struct sensorData_s { // Axis3f: see imu_types.h` // are these measurements the _raw_ sensor measurements? Or they the _filtered_ values after the Kalman filter? I would like to know which values used by the controller are raw and which are filtered? Are all of the on-board measurements _sampled_ at 1kHz?
 ```
 Axis3f acc;               // Gs  --> what does this unit mean?
  point_t position;         // m // is this the position of the center of mass of the cf2 measured by vicon? Is the sampling frequency 100Hz?
#ifdef LOG_SEC_IMU          // where is LOG_SEC_IMU defined? What is difference between accSec and acc and between gyroSec and gyro?
  Axis3f accSec;            // Gs
  Axis3f gyroSec;           // deg/s
#endif
  uint64_t interruptTimestamp; // what is this? difference with timestamp?
} sensorData_t;
```
**5d)**
```
typedef struct state_s { //
  attitude_t attitude;      // deg (legacy CF2 body coordinate system, where pitch is inverted) // So how is the CF2 body coordinate system chosen? x-axis to front of cf2, y-axis to right of cf2 and z-axis using the right hand rule (so pointing down)? What do you mean with pitch inverted? With respect to which case is pitch inverted?
  quaternion_t attitudeQuaternion; // So which convention (Hamilton or JPL?) is used for these (unit?) quaternions? Is this quaternion also corresponding to the orientation of the  CF2 body coordinate system, where pitch is inverted or is it only for attitude?
} state_t;
```
**5e)**
```
 typedef struct control_s {
  int16_t roll;
  int16_t pitch;
  int16_t yaw;
  float thrust;
} control_t; // about which axis are these control variables working (moment roll , moment pitch, moment yaw, thrust) defined? roll, pitch, yaw about which axis? Is it wrt CF2 body coordinate system, where pitch is inverted? Does thrust represent the total thrust or the thrust of 1 motor? Do these variables represent the physical moments and forces with units (e.g. Nm, Nm, Nm and N)?
// why does does this control_s not have a timestamp assigned like e.g. setpoint_t?
```

**5f)**
```
typedef enum mode_e {
  modeDisable = 0, // 
  modeAbs, // assinged automatically to 1 (previous +1)
  modeVelocity // assinged automatically to 2 (previous +1)
} stab_mode_t; // what do these modes: modeDisable, modeAbs and modeVelocity represent? Where in the code is decided if  stab_mode_t = 0,1 or 2?
```

**5g)** 
```
typedef struct setpoint_s {
  uint32_t timestamp; // is the unit in seconds or just incremental integer value without a unit?
  float thrust;  // Does this represent the total desired thrust magnitude of the 4 motors expressed in N?
  point_t position;         // m //  is this center of mass of cf2?
  velocity_t velocity;      // m/s
  acc_t acceleration;       // m/s^2
  bool velocity_body;       // true if velocity is given in body frame; false if velocity is given in world frame
  struct {
    stab_mode_t x;
    stab_mode_t y;
    stab_mode_t z;
    stab_mode_t roll;
    stab_mode_t pitch;
    stab_mode_t yaw;
    stab_mode_t quat;
  } mode;
} setpoint_t; // from where is this setpoint send to the controller_mellinger.c? From another file in the code or directly from the python API?
```
**5h)** 
Does tick represent the time step which is continuously incremented? Where can I find the code where I can see tick is incremented over time?

**Question6:**
```
struct vec target_thrust; // desired/target thrust vector expressed in world frame in N? Is this the physical force exerted by cf2?
float current_thrust; // what does this represent? Difference between wrt struct vec target_thrust? 
```

**Question7:**
` if (!RATE_DO_EXECUTE(ATTITUDE_RATE, tick))`
So the attitude controller and position controller executed at the same rate = `ATTITUDE_RATE RATE` = 500Hz? Why don't you run the position controller at a slower rate (just as in `controller_pid.c`)? I would expect position dynamics are slower than attitude dynamics?

**Question8:**
```
} else { 
        target_thrust.x = -sinf(radians(setpoint->attitude.pitch)); // where is this coming from, why -, why sin()?
    target_thrust.y = -sinf(radians(setpoint->attitude.roll)); // where is this coming from, why -, why sin()?
```

 **Question9:**
```
// In case of a timeout, the commander tries to level, ie. x/y are disabled, but z will use the previous setting
    // In that case we ignore the last feedforward term for acceleration // this is clear
    if (setpoint->mode.z == modeAbs) { // What does this mode mean?
      target_thrust.z = g_vehicleMass * GRAVITY_MAGNITUDE + kp_z  * r_error.z + kd_z  * v_error.z + ki_z  * i_error_z;
    } else {
      target_thrust.z = 1; // why = 1?
    }
  }
```
The case above is not clear to me: what do you mean with a timeout? With level you just mean keeping a fixed altitude z?

**Question10:**
```
 // Rate-controlled YAW is moving YAW angle setpoint
  if (setpoint->mode.yaw == modeVelocity) { //  what does this mode mean?
    desiredYaw = state->attitude.yaw + setpoint->attitudeRate.yaw * dt; //why setpoint+state and not setpoint-state (analoguous as position errors) for yaw error calculation?
  } else if (setpoint->mode.yaw == modeAbs) { //  what does this mode mean?
    desiredYaw = setpoint->attitude.yaw; 
  } else if (setpoint->mode.quat == modeAbs) { //  what does this mode mean?

```
**Question11:**
I have some questions about the quaternion conversion functions (`quat2rpy(), quat2rotmat()`)  in `math3d.h`.
Which RPY definition are u referring to? Rotations about which axes? Extrinsic or intrinsic rotations? Is it the same definition as in the mellinger paper ZXY Euler angles (they didn't mention xxtrinsic or intrinsic)? For the quaternions, do you use the Hamilton or the JPL convention? Could you please point me to the works where I can find these conversion formulas?

**Question12:**
```
// yaw correction (only if position control is not used) // what do you mean with yaw correction?
  if (setpoint->mode.x != modeAbs) { //  what does this mode mean?
    struct vec x_yaw = mcolumn(R, 0); // why is this the first column of R?
    x_yaw.z = 0; // why do you put this to 0?
    x_yaw = vnormalize(x_yaw); 
    struct vec y_yaw = vcross(mkvec(0, 0, 1), x_yaw); // Y = Z x X
    struct mat33 R_yaw_only = mcolumns(x_yaw, y_yaw, mkvec(0, 0, 1)); 
    target_thrust = mvmult(R_yaw_only, target_thrust); // I don't understand this one
```

**Question13:**
 `current_thrust = vdot(target_thrust, z_axis);  // I don't understand how you calculate the current trust by projecting the _(desired/target)_ target_thrust on the (current/actual) z-axis. It seems like _current_ and _target_ are mixed. Or is there an assumption you are making here?`

**Question14:**
```
 // [xC_des]
  // x_axis_desired = z_axis_desired x [sin(yaw), cos(yaw), 0]^T 
//Is it possible you forgot a – sign in the above comment line (the line is not used, but it seems wrong)? My reasoning following mellinger paper: x_axis_desired = z_axis_desired x (-y_axis_desired). y_axis_desired = [-sin(yaw), cos(yaw), 0], so that x_axis_desired = z_axis_desired x [sin(yaw), - cos(yaw), 0]^T // So I don't understand why they don't have the - cos(yaw)?
```
**Question15:**
 ```
// [yB_des]
  y_axis_desired = vnormalize(vcross(z_axis_desired, x_c_des)); // Is the following correct: you can use  x_c_des (instead of  x_B_des, which you don’t know yet) because  x_c_des and  x_B_des are both in the  x_B_des -  z_B_des plane? This reasoning only works if it are (as assumed in mellinger paper) ZXY Euler angles, but with intrinsic rotations (about the new axis). The fact that it uses intrinsic rotations was not explicitely mentioned, but I wanted to check if this is correct to you?
```

**Question16:**
```
 pitch_desired = degrees(asinf(-x_axis_desired.z)); 
  roll_desired  = degrees(atan2f(y_axis_desired.z, z_axis_desired.z));
// can you point to the conversion formulas you are using?If you are using ZXY Euler angles as described in mellinger paper, I don't see how this conversion can be correct.
```

**Question17:**
```
// struct mat33 eRM = msub(mmult(Rdes_transpose, R), mmult(R_transpose, Rdes)); // Why didn't you put the factor 1/2 as in mellinger paper?
  // if this below is the vee operator, could you please point the definition used in a paper where this definition is given?
  // eR.x = eRM.m[2][1];      
  // eR.y = -eRM.m[0][2];
  // eR.z = eRM.m[1][0];

  // Fast version (generated using Mathematica)
  // So why is this version faster and how did you compute it? You still seem to be using information of the rotation matrix and not only information of quaternions.
```
**Question18:**
**18a)**
```
// Account for Crazyflie coordinate system // could you point me to figures so I know which axis definitions are used? 
  eR.y = -eR.y;  // why -, what is the difference between the used coordinate system before and the on u sed by the crazyflie? I would assume you start from a right handed coordinate system, but if you invert the y-axis, you obtain a left handed coordinate system.
```
**18b)** 
`float stateAttitudeRatePitch = -radians(sensors->gyro.y); // why again a - for these sensor measurements?`
**18c)** 
`ew.y = -radians(setpoint->attitudeRate.pitch) - stateAttitudeRatePitch; // why -?`
**18d)**
```
// Integral Error
  i_error_m_x += (-eR.x) * dt; // why minus signs: -eR.x, -eR.y and -eR.z?
  i_error_m_x = clampNew(i_error_m_x, -i_range_m_xy, i_range_m_xy);
```

**Question19:**
```
if (prev_omega_roll == prev_omega_roll) { /*d part initialized*/  //What does /*d part initialized*/ mean? Seems this equality is always valid, so I don't understand its use?
    err_d_roll = ((radians(setpoint->attitudeRate.roll) - prev_setpoint_omega_roll) - (stateAttitudeRateRoll - prev_omega_roll)) / dt;
    err_d_pitch = (-(radians(setpoint->attitudeRate.pitch) - prev_setpoint_omega_pitch) - (stateAttitudeRatePitch - prev_omega_pitch)) / dt;
  } // I also  don't understand why dividing by everything by dt, attitudeRate and prev_setpoint_omega_pitch are already speeds so you would get an acceleration ? why again the - sign for err_d_pitch? I read this: ((increment of rateSetpoint)-(increment of rate actual))/dt. In the crazyswarm paper there is derivative action on omega and not on omega dot.
```

**Question20:**
` control->thrust = massThrust * current_thrust; // What is massThrust, and why is this value chosen? Can I change this value or should it remain as defined? I don’t understand in which lines of the code the forces are the physical forces/moments expressed in N/Nm.`

**Question21:**
 ```
control->roll = clampNew(M.x, -32000, 32000); // why the value 32000, why this choice?
    control->pitch = clampNew(M.y, -32000, 32000);
    control->yaw = clampNew(-M.z, -32000, 32000); // why - now for z?
```
Are the M the physical control moments about the x,y and z axis in Nm?

**Question22:**
In `power_distribution_stock.c`:
```
void powerDistribution(const control_t *control)
{
  #ifdef QUAD_FORMATION_X // this cross X formation is the default for the crazyflie 2.0
// X: points to the front of the cf?
// Y: points to the right of the cf?
// Z=X cross Y: points down?
    int16_t r = control->roll / 2.0f; // why should these (moments?) be divided by 2?
    int16_t p = control->pitch / 2.0f;
    motorPower.m1 = limitThrust(control->thrust - r + p + control->yaw);  // are r, p moments or forces?
    motorPower.m2 = limitThrust(control->thrust - r - p - control->yaw);
    motorPower.m3 =  limitThrust(control->thrust + r - p + control->yaw);
    motorPower.m4 =  limitThrust(control->thrust + r + p - control->yaw);
// why is the control->thrust (which I think is the total thrust of all 4 motors) not divided by 4 first? Is this the thrust assigned in controller_mellinger.c?
```

**Question 23:**
in `motors.c`:
```
// Ithrust is thrust mapped for 65536 <==> 60 grams
void motorsSetRatio(uint32_t id, uint16_t ithrust)
{
  if (isInit) {
    uint16_t ratio;
    ASSERT(id < NBR_OF_MOTORS);
    ratio = ithrust;
  #ifdef ENABLE_THRUST_BAT_COMPENSATED
    if (motorMap[id]->drvType == BRUSHED)
    {
      float thrust = ((float)ithrust / 65536.0f) * 60; // so this is thrust expressed in grams (so a force if you would also multiply by gravity constant?)
      // is there any documention (paper/work) where I can find this mapping explained?
      float volts = -0.0006239f * thrust * thrust + 0.088f * thrust; // is there any documention where I can find this mapping?
      float supply_voltage = pmGetBatteryVoltage(); // how significant is the influence of the battery voltage drop on the thrust coefficients?
      float percentage = volts / supply_voltage;
      percentage = percentage > 1.0f ? 1.0f : percentage; // what does this line mean?
      ratio = percentage * UINT16_MAX; // what does UINT16_MAX represent?
      motor_ratios[id] = ratio;
    }
```

**Comment by whoenig** [comment]
Hi,
Those are too many questions for me to respond to - you seem to have several subquestions in a number of the "main" questions... For some of the question, you will need to read the rest of the code of the firmware, to understand units and conventions. Some of your confusion can be clarified by two facts:
1. The firmware supports different kinds of setpoints, for example for velocity control, or position control. Thus, the controller has to support different "modes".
2. The units in the firmware are not SI units. The units in the controller itself, are also non standard, i.e., there is no physical meaning.

About some of your questions:
1. This might be a "bug". You can include "stabilizer_types.h" directly, instead.
2. Static in global scope in C just means that the variable cannot be used from a different C file.
3. This bounds the I-part and can be obtained by guessing how large the steady-state error can be. This is common for PID controllers.
4. They are called using function pointers, see controller.c
5a. This uses a union, so you get different names for the same components.
5b. Hamilton
23. https://wiki.bitcraze.io/misc:investigations:thrust

**Comment by emmasmith100** [comment]
Hi @whoenig,
Thanks for considering some of my questions.
I am very sorry if I asked too many questions in one post. 
I don't know which rules I should follow if I ask questions here, that's not clear to me at all.
I just listed all the questions I had when I went chronologically (and multiple times) through the mellinger paper, `controller_mellinger.c`, and related files.
I just thought that these questions could help me and several other people in the future who start working with the crazyflie.

My follow up questions on your answers to part of my questions:
> For some of the question, you will need to read the rest of the code of the firmware, to understand units and conventions

I would be very happy if you could point me to files where it is explicitly stated which axis definitions are used. In the files I referred to in my questions (mainly `math3d.h`) I have not seen any axis definitions, neither definitions of Euler angle conventions used (axis order, intrinsic/extrinsic), or quaternions (Hamilton/JPL). Because of your answer I know you use the Hamilton convention, but it was not clear from `math3d.h`. So what's the convention used for RPY?
Halfway in controller_mellinger.c there start appearing many - signs to convert to other axis definitions. It is not clear which frame definition wrt CF2 you consider in the first part for the code and which in the second part. Note also in the mellinger paper they define axis on a quadrotor along the lines that connect 2 motors. The crazyflie uses the X configuration, which is different.

> The units in the firmware are not SI units. The units in the controller itself, are also non standard, i.e., there is no physical meaning.

Thanks for pointing me to [https://wiki.bitcraze.io/misc:investigations:thrust](https://wiki.bitcraze.io/misc:investigations:thrust), now I understand  the mapping `float volts = -0.0006239f * thrust * thrust + 0.088f * thrust;` as defined in `motors.c`.
Though still it is unclear to me in `power_distribution_stock.c` why you divide by 2:
```
int16_t r = control->roll / 2.0f;
int16_t p = control->pitch / 2.0f;
```
If you cannot answer my other questions, do you know someone who you think can respond to my questions?
Thank you for your time!

**Comment by whoenig** [comment]
I didn't want to discourage you to ask questions and I hope that you'll find all the answer eventually. All I wanted to say is that this project is mostly run in free time, so questions that are very time consuming might not get answered.

For the conventions, there might be no direct comments in the code, but you can infer from the equations that are used in the code.

For the negative signs and the power distribution: Unfortunately, there are many inconsistencies in the firmware. You can find a non-exhaustive list here: https://lib.dr.iastate.edu/etd/15575/ (Appendix A). Essentially, those signs compensate for those issues.

You can ask generic firmware questions in the official forum, which has more people reading and writing there than the github issues here.

**Comment by emmasmith100** [comment]
Thanks for your answer @whoenig.
Unfortunately, the download link seems not to be working.
Could you please send me (emma.smith100@hotmail.com) the PDF version?
Thanks!

**Comment by whoenig** [comment]
I sent an email.

**Comment by emmasmith100** [comment]
Thank you! This will help me forward!
